# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExotelVoiceSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExotelVoiceSample
   pod 'IQKeyboardManagerSwift', '6.3.0'
   pod 'DropDown'
   pod 'Alamofire', '~> 4.0'
   pod 'SVProgressHUD'
   pod 'Firebase/Analytics', '8.13.0'
   pod 'Firebase/Messaging', '8.13.0'
   pod 'Firebase/Crashlytics'
   pod 'SQLite.swift', '~> 0.11.5'
end
